### PR TITLE
limit number length in redis with toFixed(1)

### PR DESCRIPTION
**Pull request by jimyang2008**

### CODE REVIEW

**Review by drahnieR — CHANGES_REQUESTED** [review]
scan has already implemented in `redis_manager`, consider using the wrapper instead
https://github.com/firewalla/firewalla/blob/1ed512646b98d41830d58b199aa4eaf27eac95b4/util%2Fredis_manager.js#L36

**Comment by drahnieR** [comment]
also, does float number fetched in `getNetworkMonitorData` needs to be parsed?

**Comment by jimyang2008** [comment]
> scan has already implemented in `redis_manager`, consider using the wrapper instead
> https://github.com/firewalla/firewalla/blob/1ed512646b98d41830d58b199aa4eaf27eac95b4/util%2Fredis_manager.js#L36

Code updated to use`rclient.scanAll(...)`

**Comment by jimyang2008** [comment]
> also, does float number fetched in `getNetworkMonitorData` needs to be parsed?

Added `parseFloat` to the code where saves the data into redis.

**Review by drahnieR — APPROVED** [review]

**Pull request merged**
