### PR TITLE
support running firewalla on docker environment

### PR DESCRIPTION
**Pull request by MelvinTo**
not able to link with app yet.

### CODE REVIEW

**Comment by jerrchen** [comment]
your build failed.  need to fix it later.  will merge it now

**Comment by jerrchen** [comment]
also isProduction may not work all the time, the enviroment variable some times don't get passed, so need to check if that production file is there.

**Comment by MelvinTo** [comment]
Failed is because the user used in travis ci is "travis", not "pi". To fix it, will add a minor change to use $USER instead of pi.

**Comment by MelvinTo** [comment]
But not sure whether "travis" is really supported throughout the entire code base, the current build will pass with the minor fix above

**Comment by MelvinTo** [comment]
@xuanxuandog

**Pull request merged**
